- name: Use Git protocol v2
  command: git config --global protocol.version 2

- name: Disable Spotlight indexing
  command: mdutil -i off /
  become: true

- name: Delete bash history
  file:
    state: absent
    path: /Users/travis/{{ item }}
  loop:
  - .bash_history
  - .bash_sessions

- name: Empty trash
  file:
    state: absent
    path: /Users/travis/.Trash
